<?php

/*
|--------------------------------------------------------------------------
| Saudi Arabia Cities
|--------------------------------------------------------------------------
|
| Static lookup used by the admin schools form so we don't need a DB table
| for what is essentially a fixed list. Key is a stable lowercase slug
| used as the stored value on `schools.city`; value is the bilingual label.
|
*/

return [
    'riyadh'         => ['ar' => 'الرياض',        'en' => 'Riyadh'],
    'jeddah'         => ['ar' => 'جدة',           'en' => 'Jeddah'],
    'mecca'          => ['ar' => 'مكة المكرمة',   'en' => 'Mecca'],
    'medina'         => ['ar' => 'المدينة المنورة', 'en' => 'Medina'],
    'dammam'         => ['ar' => 'الدمام',        'en' => 'Dammam'],
    'al_khobar'      => ['ar' => 'الخبر',         'en' => 'Al Khobar'],
    'dhahran'        => ['ar' => 'الظهران',       'en' => 'Dhahran'],
    'taif'           => ['ar' => 'الطائف',        'en' => 'Taif'],
    'tabuk'          => ['ar' => 'تبوك',          'en' => 'Tabuk'],
    'buraidah'       => ['ar' => 'بريدة',         'en' => 'Buraidah'],
    'unaizah'        => ['ar' => 'عنيزة',         'en' => 'Unaizah'],
    'al_rass'        => ['ar' => 'الرس',          'en' => 'Al Rass'],
    'abha'           => ['ar' => 'أبها',          'en' => 'Abha'],
    'khamis_mushait' => ['ar' => 'خميس مشيط',     'en' => 'Khamis Mushait'],
    'najran'         => ['ar' => 'نجران',         'en' => 'Najran'],
    'jazan'          => ['ar' => 'جازان',         'en' => 'Jazan'],
    'sabya'          => ['ar' => 'صبيا',          'en' => 'Sabya'],
    'hail'           => ['ar' => 'حائل',          'en' => 'Hail'],
    'al_jouf'        => ['ar' => 'الجوف',         'en' => 'Al Jouf'],
    'sakaka'         => ['ar' => 'سكاكا',         'en' => 'Sakaka'],
    'arar'           => ['ar' => 'عرعر',          'en' => 'Arar'],
    'rafha'          => ['ar' => 'رفحاء',         'en' => 'Rafha'],
    'qurayyat'       => ['ar' => 'القريات',       'en' => 'Qurayyat'],
    'al_bahah'       => ['ar' => 'الباحة',        'en' => 'Al Bahah'],
    'al_qunfudhah'   => ['ar' => 'القنفذة',       'en' => 'Al Qunfudhah'],
    'al_lith'        => ['ar' => 'الليث',         'en' => 'Al Lith'],
    'al_jumum'       => ['ar' => 'الجموم',        'en' => 'Al Jumum'],
    'rabigh'         => ['ar' => 'رابغ',          'en' => 'Rabigh'],
    'yanbu'          => ['ar' => 'ينبع',          'en' => 'Yanbu'],
    'al_ula'         => ['ar' => 'العلا',         'en' => 'Al Ula'],
    'al_wajh'        => ['ar' => 'الوجه',         'en' => 'Al Wajh'],
    'duba'           => ['ar' => 'ضبا',           'en' => 'Duba'],
    'haql'           => ['ar' => 'حقل',           'en' => 'Haql'],
    'tayma'          => ['ar' => 'تيماء',         'en' => 'Tayma'],
    'al_hofuf'       => ['ar' => 'الهفوف',        'en' => 'Al Hofuf'],
    'al_mubarraz'    => ['ar' => 'المبرز',        'en' => 'Al Mubarraz'],
    'qatif'          => ['ar' => 'القطيف',        'en' => 'Qatif'],
    'jubail'         => ['ar' => 'الجبيل',        'en' => 'Jubail'],
    'ras_tanura'     => ['ar' => 'رأس تنورة',     'en' => 'Ras Tanura'],
    'khafji'         => ['ar' => 'الخفجي',        'en' => 'Khafji'],
    'hafar_albatin'  => ['ar' => 'حفر الباطن',    'en' => 'Hafar Al Batin'],
    'al_kharj'       => ['ar' => 'الخرج',         'en' => 'Al Kharj'],
    'al_aflaj'       => ['ar' => 'الأفلاج',       'en' => 'Al Aflaj'],
    'al_sulayyil'    => ['ar' => 'السليل',        'en' => 'Al Sulayyil'],
    'al_dawadmi'     => ['ar' => 'الدوادمي',      'en' => 'Al Dawadmi'],
    'al_quwaiiyah'   => ['ar' => 'القويعية',      'en' => 'Al Quwaiiyah'],
    'al_majmaah'     => ['ar' => 'المجمعة',       'en' => 'Al Majmaah'],
    'shaqra'         => ['ar' => 'شقراء',         'en' => 'Shaqra'],
    'huraymila'      => ['ar' => 'حريملاء',       'en' => 'Huraymila'],
    'al_zulfi'       => ['ar' => 'الزلفي',        'en' => 'Al Zulfi'],
    'al_ghat'        => ['ar' => 'الغاط',         'en' => 'Al Ghat'],
    'al_artawiya'    => ['ar' => 'الأرطاوية',     'en' => 'Al Artawiya'],
    'thadeq'         => ['ar' => 'ثادق',          'en' => 'Thadeq'],
    'al_diriyah'     => ['ar' => 'الدرعية',       'en' => 'Al Diriyah'],
    'al_muzahmiya'   => ['ar' => 'المزاحمية',     'en' => 'Al Muzahmiya'],
    'al_hareeq'      => ['ar' => 'الحريق',        'en' => 'Al Hareeq'],
    'al_kharkhir'    => ['ar' => 'الخرخير',       'en' => 'Al Kharkhir'],
    'wadi_aldawasir' => ['ar' => 'وادي الدواسر',  'en' => 'Wadi Al Dawasir'],
    'bisha'          => ['ar' => 'بيشة',          'en' => 'Bisha'],
    'tathleeth'      => ['ar' => 'تثليث',         'en' => 'Tathleeth'],
    'al_namas'       => ['ar' => 'النماص',        'en' => 'Al Namas'],
    'tanouma'        => ['ar' => 'تنومة',         'en' => 'Tanouma'],
    'baljurashi'     => ['ar' => 'بلجرشي',        'en' => 'Baljurashi'],
    'al_mandaq'      => ['ar' => 'المندق',        'en' => 'Al Mandaq'],
    'al_aqiq'        => ['ar' => 'العقيق',        'en' => 'Al Aqiq'],
    'sharurah'       => ['ar' => 'شرورة',         'en' => 'Sharurah'],
    'hubuna'         => ['ar' => 'حبونا',         'en' => 'Hubuna'],
    'thar'           => ['ar' => 'ثار',           'en' => 'Thar'],
    'sajir'          => ['ar' => 'ساجر',          'en' => 'Sajir'],
    'al_uyaynah'     => ['ar' => 'العيينة',       'en' => 'Al Uyaynah'],
    'al_jubaila'     => ['ar' => 'الجبيلة',       'en' => 'Al Jubaila'],
    'al_oyoun'       => ['ar' => 'العيون',        'en' => 'Al Oyoun'],
    'al_kahafah'     => ['ar' => 'الكهفة',        'en' => 'Al Kahafah'],
    'al_hayit'       => ['ar' => 'الحائط',        'en' => 'Al Hayit'],
    'baqaa'          => ['ar' => 'بقعاء',         'en' => 'Baqaa'],
    'al_shinan'      => ['ar' => 'الشنان',        'en' => 'Al Shinan'],
    'al_ghazala'     => ['ar' => 'الغزالة',       'en' => 'Al Ghazala'],
    'turaif'         => ['ar' => 'طريف',          'en' => 'Turaif'],
    'al_uwayqilah'   => ['ar' => 'العويقيلة',     'en' => 'Al Uwayqilah'],
    'dawmat_aljandal'=> ['ar' => 'دومة الجندل',   'en' => 'Dawmat Al Jandal'],
    'tabarjal'       => ['ar' => 'طبرجل',         'en' => 'Tabarjal'],
    'badr'           => ['ar' => 'بدر',           'en' => 'Badr'],
    'al_henakiya'    => ['ar' => 'الحناكية',      'en' => 'Al Henakiya'],
    'mahd_aldhahab'  => ['ar' => 'مهد الذهب',     'en' => 'Mahd Al Dhahab'],
    'khaybar'        => ['ar' => 'خيبر',          'en' => 'Khaybar'],
    'al_eis'         => ['ar' => 'العيص',         'en' => 'Al Eis'],
    'wadi_alfar'     => ['ar' => 'وادي الفرع',    'en' => 'Wadi Al Far'],
    'al_mahd'        => ['ar' => 'المهد',         'en' => 'Al Mahd'],
    'al_kamil'       => ['ar' => 'الكامل',        'en' => 'Al Kamil'],
    'khulais'        => ['ar' => 'خليص',          'en' => 'Khulais'],
    'turbah'         => ['ar' => 'تربة',          'en' => 'Turbah'],
    'al_khurmah'     => ['ar' => 'الخرمة',        'en' => 'Al Khurmah'],
    'ranyah'         => ['ar' => 'رنية',          'en' => 'Ranyah'],
    'mahayil'        => ['ar' => 'محايل عسير',    'en' => 'Mahayil Asir'],
    'rijal_almaa'    => ['ar' => 'رجال ألمع',     'en' => 'Rijal Alma'],
    'sabt_alalaya'   => ['ar' => 'سبت العلايا',   'en' => 'Sabt Al Alaya'],
    'al_birk'        => ['ar' => 'البرك',         'en' => 'Al Birk'],
    'al_aridah'      => ['ar' => 'العارضة',       'en' => 'Al Aridah'],
    'abu_arish'      => ['ar' => 'أبو عريش',      'en' => 'Abu Arish'],
    'samtah'         => ['ar' => 'صامطة',         'en' => 'Samtah'],
    'al_darb'        => ['ar' => 'الدرب',         'en' => 'Al Darb'],
    'farasan'        => ['ar' => 'فرسان',         'en' => 'Farasan'],
    'al_eidabi'      => ['ar' => 'العيدابي',      'en' => 'Al Eidabi'],
    'baish'          => ['ar' => 'بيش',           'en' => 'Baish'],
];
